In [1]:
# 4.1.2 누락된 값 다루기(다른 값으로 대체하기)
# 실습에 필요한 패키지를 불러옵니다.
from sklearn.impute import SimpleImputer
import numpy as np

# 누락된 값을 포함한 데이터를 준비합니다.
X = np.array([[1, 6, 3],
                      [4, 5, 3],
                      [3, 7, 5],
                      [2, 5, None],
                       [8, 5, 1]])

# 누락된 값을 중앙값으로 대체하는 SimpleImputer 객체를 생성합니다.
imputer = SimpleImputer(strategy='median')

# 누락된 값을 중앙값으로 대체합니다.
X_imputed = imputer.fit_transform(X)

# 결과를 출력합니다.
print(X_imputed)

[[1. 6. 3.]
 [4. 5. 3.]
 [3. 7. 5.]
 [2. 5. 3.]
 [8. 5. 1.]]


In [2]:
# 학습, 테스트 데이터를 준비합니다.
X_train = np.array([[1, 6, 3],
                               [4, 5, 3],
                               [3, 7, 5]])

X_test = np.array([[1, 5, None],
                              [2, None, 4]])

# 누락된 값을 평균값으로 대체하는 SimpleImputer 객체를 생성하고 학습시킵니다.
imputer = SimpleImputer(strategy='mean')
imputer.fit(X_train)

# 누락된 값을 학습 세트의 평균값으로 대체합니다.
X_imputed = imputer.transform(X_test)

# 결과를 출력합니다.
print(X_imputed)

[[1.         5.         3.66666667]
 [2.         6.         4.        ]]


In [3]:
# 실습에 필요한 패키지를 불러옵니다.
from fancyimpute import KNN

# 누락된 값을 포함한 데이터를 준비합니다.
X = np.array([[1, 6, 3],
              [4, 5, 3],
              [3, 7, 5],
              [1, 5, None],
              [2, None, 4]])

# K 최근접 이웃 알고리즘을 이용해서 누락된 값을 예측합니다.
X = KNN(k=3).fit_transform(X)

# 결과를 출력합니다.
print(X)

Imputing row 1/5 with 0 missing, elapsed time: 0.001
[[1.         6.         3.        ]
 [4.         5.         3.        ]
 [3.         7.         5.        ]
 [1.         5.         3.46153846]
 [2.         6.         4.        ]]
