In [2]:
# 넘파이 패키지를 np라는 별칭으로 불러옵니다.
import numpy as np

In [3]:
# 넘파이 배열을 만듭니다.
arr = np.array([1, 3, 5, 7])

# 넘파이 배열을 출력합니다.
print('넘파이 배열: {}'.format(arr))

넘파이 배열: [1 3 5 7]


In [4]:
# 넘파이 배열의 형태를 출력합니다.
print('배열 형태: {}'.format(arr.shape))

# 넘파이 배열의 데이터 타입을 출력합니다.
print('데이터 타입: {}'.format(type(arr)))

배열 형태: (4,)
데이터 타입: <class 'numpy.ndarray'>


In [5]:
# 넘파이 배열이 가진 요소의 데이터 타입을 출력합니다.
print('배열 요소의 데이터 타입: {}'.format(arr.dtype))

배열 요소의 데이터 타입: int64


In [6]:
# 2차원 넘파이 배열을 생성합니다.
arr = np.array([[1, 3, 5, 7], [1, 2, 3, 4]])

# 2차원 넘파이 배열을 출력합니다.
print('넘파이 배열:\n{}'.format(arr))

넘파이 배열:
[[1 3 5 7]
 [1 2 3 4]]


In [7]:
# 2차원 넘파이 배열의 형태를 출력합니다.
print('배열 형태: {}'.format(arr.shape))

배열 형태: (2, 4)


In [8]:
# 모든 요소 값이 0인 3행, 3열의 2차원 넘파이 배열을 생성합니다..
arr= np.zeros((3, 3))

# 2차원 넘파이 배열을 출력합니다.
print('넘파이 배열:\n{}'.format(arr))

넘파이 배열:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# 모든 요소 값이 1인 2행, 4열의 2차원 넘파이 배열을 생성합니다..
arr= np.zeros((3, 3))

# 2차원 넘파이 배열을 출력합니다.
print('넘파이 배열:\n{}'.format(arr))

넘파이 배열:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# 0과 1 사이의 무작위 실수 값을 요소로 갖는 2행, 4열의 2차원 넘파이 배열을 생성합니다.
arr = np.random.rand(2, 4)

# 2차원 넘파이 배열을 출력합니다.
print('넘파이 배열:\n{}'.format(arr))

넘파이 배열:
[[0.90982565 0.26898233 0.19174604 0.69591893]
 [0.37268674 0.75638848 0.42360646 0.97285946]]


In [11]:
# 5와 10 사이의 무작위 정수 값을 요소로 갖는 2행, 4열의 2차원 넘파이 배열을 생성합니다.
arr = np.random.randint(5, 10, size=(2, 4))

# 2차원 넘파이 배열을 출력합니다.
print('넘파이 배열:\n{}'.format(arr))

넘파이 배열:
[[7 6 6 8]
 [9 8 7 6]]


In [12]:
# 일정한 간격의 정수 값을 갖는 넘파이 배열을 생성합니다.
arr1 = np.arange(1, 10, 1)
# 생성된 넘파이 배열을 출력합니다.
print('넘파이 배열1:\n{}'.format(arr1))

# 일정한 간격의 실수 값을 갖는 넘파이 배열을 생성합니다.
arr2 = np.arange(0.1, 1, 0.1)
# 생성된 넘파이 배열을 출력합니다.
print('넘파이 배열2:\n{}'.format(arr2))

넘파이 배열1:
[1 2 3 4 5 6 7 8 9]
넘파이 배열2:
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [13]:
# 파이썬 리스트를 만듭니다.
list_data = [1, 2, 3, 4]

# 넘파이 배열을 만듭니다.
array_data = np.array([1, 2, 3, 4])

# 파이썬 리스트와 넘파이 배열에 각각 곱셈 연산을 적용한 결과를 출력합니다.
print('파이썬 리스트 곱셈 연산 결과: {}'.format(list_data * 2))
print('넘파이 배열 곱셈 연산 결과: {}'.format(array_data * 2))

파이썬 리스트 곱셈 연산 결과: [1, 2, 3, 4, 1, 2, 3, 4]
넘파이 배열 곱셈 연산 결과: [2 4 6 8]


In [14]:
# 넘파이 배열을 만듭니다.
array_data = np.array([1, 2, 3, 4])

# 조건에 해당하는 마스크를 만듭니다.
array_mask = array_data > 2

# 마스크를 이용해 넘파이 배열에서 원하는 값만 추출합니다.
filtered_array = array_data[array_mask]

# 마스크와 마스크를 이용해 필터링 된 배열 정보를 출력합니다.
print('마스크 정보: {}'.format(array_mask))
print('마스크를 이용해 필터링 된 배열: {}'.format(filtered_array))

마스크 정보: [False False  True  True]
마스크를 이용해 필터링 된 배열: [3 4]
